### ISSUE TITLE
Use in Cordova project ?

### ISSUE THREAD

**Issue by mistic100** [Pushwoosh/pushwoosh-windows-sdk#5]
As there is no news on Pushwoosh/pushwoosh-phonegap-3.0-plugin#107 I try to use this SDK on my Cordova app. But I can't find how to add the dependency to the project.

I am new to Windows development, is this even possible ? Any other alternative ?
Thank you

**Comment by shaders** [comment]
The support for Windows development has been added (4.0.0).
