### ISSUE TITLE
Pushwoosh CustomData not arriving on Windows Phone

### ISSUE THREAD

**Issue by rickrvo** [Pushwoosh/pushwoosh-windows-sdk#8]
Hi,

The ToastPush object that arrives in OnPushAccepted was working fine and suddenly started arriving with userData field as empty even when CustomData is set.

This is what arrives in WP: {"hash":"3e","html":-1,"url":null,"content":"A film was automatically created for you by Stayfilm. Check it out!","userdata":"","onStart":false}

So it doesn’t matter where the push is being sent. Sending from my PHP server and pushwoosh website both arrives with userData field as empty.

We've debugged the request arriving on the Cordova platform using Android and the push arrived with the userdata filled correctly.
There are much more details that pushwoosh SDK for cordova gives us that Windows Phone SDK ToastPush object doesn’t.

This is what arrives in Cordova pushwoosh SDK client:

> PushServ.process() Eventbubbles: truecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0isTrusted: falsenotification: Objectcollapse_key: "do_not_collapse"foreground: falsegoogle.message_id: "0:1481648487255250a88abbf9fd7ecd"google.sent_time: 1481648487240onStart: truepw_msg: "1"title: "hey push"u: "{"id":"41316577-a6d9-4636-aebf-d17b5d2c9f06"}"userdata: Objectid: "41316577-a6d9-4636-aebf-d17b5d2c9f06"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()__proto__: Objectpath: Array[2]returnValue: truesrcElement: documenttarget: documenttimeStamp: 3915.4700000000003type: "push-notification"__proto__: Event

It arrived the CustomData which is {”id”:"41316577-a6d9-4636-aebf-d17b5d2c9f06"}. So apparently the problem is in Pushwoosh WindowsPhone 8  SDK.

Does anyone know what might be happening?

Kind regards,
Henrique

**Comment by rickrvo** [comment]
if it helps... here is the log from the PHP side:

Gomoob\Pushwoosh\Model\Request\CreateMessageRequest Object
(
    [application:Gomoob\Pushwoosh\Model\Request\CreateMessageRequest:private] => 
    [applicationsGroup:Gomoob\Pushwoosh\Model\Request\CreateMessageRequest:private] => 
    [auth:Gomoob\Pushwoosh\Model\Request\CreateMessageRequest:private] => 
    [notifications:Gomoob\Pushwoosh\Model\Request\CreateMessageRequest:private] => Array
        (
            [0] => Gomoob\Pushwoosh\Model\Notification\Notification Object
                (
                    [aDM:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [android:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [blackBerry:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [chrome:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [conditions:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [content:Gomoob\Pushwoosh\Model\Notification\Notification:private] => test
                    [data:Gomoob\Pushwoosh\Model\Notification\Notification:private] => Array
                        (
                            [id] => 6c94d40f-9a46-4a7e-9cc0-e60eabaad177
                        )
                    [devices:Gomoob\Pushwoosh\Model\Notification\Notification:private] => Array
                        (
                            [0] => 0252E6174427C977B44894C109648AB1B9F5DC7B
                            [1] => 3853C61BA6E5DC65B28CA8C8F244E30F73D4A9BB
                            [2] => 3E13095BE8574958A7022646387F6C9B88815EF2
                            [3] => 420eee5eb78ba4a9e2afbe4794e1c2f0db7dbb3800343a44fc010d56d8726a1d
                            [4] => 4D4D79DE-EBB4-4F6B-9151-59F785C1F67A
                            [5] => 68ea3bfe05d2137cdd05fbb38f1881fc3ff7f3bc9c79716484e20ac5e70af789
                            [6] => AF5A8B6B2B7C96493C44353E0E495DFCD3CB46A3
                            [7] => a17436669356d384b51c8fcf58558e466970e307225413d67fc383ecf11f2c6a
                            [8] => c768532db3223198005df2d335a7f7766dbb5c3db37ce2c2e7c6796bf66adc8f
                            [9] => cJkZ-86_DNQ:APA91bG1uKeKM3Kfz49kujVPRx0oEt5o_qWTrJSIyOTdp_2kMSkNPe6iVvTWFA1Jek7cJ6vTKLyjkm8QErDj0f70egKxK_9tqwUP2SGugwZXrsLv7UkUz3yuQhqVE_qKJmmFcl3javC5
                            [10] => eVNkXZG35pU:APA91bF48kOv1n7H4hST1TfGkAtgbUHGqNdACW265Dhj5kDjgmDfJrg95Xe_rGKpXBsrhFx6IjKxrYVwTBdpfWZxo-zTNhC_yHdFszhN8MmKzaC3RJMmAwvawNwM1E2NfhbS01Xafadj
                        )
                    [filter:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [ignoreUserTimezone:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 1
                    [iOS:Gomoob\Pushwoosh\Model\Notification\Notification:private] => Gomoob\Pushwoosh\Model\Notification\IOS Object
                        (
                            [apnsTrimContent:Gomoob\Pushwoosh\Model\Notification\IOS:private] => 
                            [badges:Gomoob\Pushwoosh\Model\Notification\IOS:private] => +1
                            [categoryId:Gomoob\Pushwoosh\Model\Notification\IOS:private] => 
                            [rootParams:Gomoob\Pushwoosh\Model\Notification\IOS:private] => 
                            [sound:Gomoob\Pushwoosh\Model\Notification\IOS:private] => 
                            [ttl:Gomoob\Pushwoosh\Model\Notification\IOS:private] => 
                            [trimContent:Gomoob\Pushwoosh\Model\Notification\IOS:private] => 
                        )
                    [link:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [mac:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [minimizeLink:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [pageId:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [platforms:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [safari:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [sendDate:Gomoob\Pushwoosh\Model\Notification\Notification:private] => now
                    [wNS:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                    [wP:Gomoob\Pushwoosh\Model\Notification\Notification:private] => 
                )
        )
)
Gomoob\Pushwoosh\Model\Response\CreateMessageResponse Object
(
    [response:Gomoob\Pushwoosh\Model\Response\CreateMessageResponse:private] => Gomoob\Pushwoosh\Model\Response\CreateMessageResponseResponse Object
        (
            [messages:Gomoob\Pushwoosh\Model\Response\CreateMessageResponseResponse:private] => Array
                (
                    [0] => 62F3-8A3AEE2E-252E273C
                )
        )
    [statusCode:protected] => 200
    [statusMessage:protected] => OK
)

**Comment by wfhm** [comment]
Hi,

The fix to this issue will be released during this week, and as soon as it is done we will update you via this thread.

**Comment by wfhm** [comment]
Hi,

We've just rolled out the fix to this issue, please try once again and let us know about the results.

**Comment by simonsturge** [comment]
Hi wfhm

Is the fix server side only?

We are also seeing an issue where push tokens fail to come through. It would appear that sometimes it gets stuck on 'opening channel'. Is this something that's been reported in the past?

**Comment by wfhm** [comment]
Hi Simon,

Yep, the fix is server side only, no additional code changes required. 

As for the token issue, could you please be a bit more specific? What do you mean by "tokens fail to come through"? Is it a problem of receiving tokens from MPNS or sending it to Pushwoosh servers? Also providing us with a log describing the issue would be highly appreciated.
